version: '3.8'
services:
  test-db:
    image: mysql
    container_name: test
    ports:
      - "3307:3306"
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: foadas1381
      MYSQL_DB: test